### ISSUE TITLE
can't see polintcloud in rviz

### ISSUE THREAD

**Issue by ZhenpengChenCode** [Livox-SDK/livox_ros_driver2#10]
Hello, I run the command "roslaunch livox_ros_driver2 rviz_HAP.launch", it shows that lidar has been successfully initialized, but I can't see any point cloud on rviz.
![Screenshot from 2022-12-22 15-48-30](https://user-images.githubusercontent.com/15834233/209085324-de8e8026-398b-4f16-a835-a957ad7fe79b.png)

**Comment by ahmadchalhoub** [comment]
Hello. I am running into the same problem @ZhenpengChenCode. Have you found a solution for this yet?

**Comment by ZhenpengChenCode** [comment]
> Hello. I am running into the same problem @ZhenpengChenCode. Have you found a solution for this yet?

No yet.

**Comment by ZhenpengChenCode** [comment]
> 

Hi, I found out that the problem was that our ethernet cable was connected to the wrong port. You can check if you can ping 192.168.1.100. If the pings are different, it means that the data link is not connected.

**Comment by Livox-Infra** [comment]
> > 
> 
> Hi, I found out that the problem was that our ethernet cable was connected to the wrong port. You can check if you can ping 192.168.1.100. If the pings are different, it means that the data link is not connected.

hi @ZhenpengChenCode , sorry for late reply. Is there any problem for connection to the lidar?

**Comment by ZhenpengChenCode** [comment]
> > > 
> > 
> > 
> > Hi, I found out that the problem was that our ethernet cable was connected to the wrong port. You can check if you can ping 192.168.1.100. If the pings are different, it means that the data link is not connected.
> 
> hi @ZhenpengChenCode , sorry for late reply. Is there any problem for connection to the lidar?

We found that the point cloud data could not be received because of the wrong connection of the Ethernet port. It's resolved now, thanks.
