### ISSUE TITLE
./build.sh ROS1  failed

### ISSUE THREAD

**Issue by WangY69** [Livox-SDK/livox_ros_driver2#11]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIVOX_LIDAR_SDK_LIBRARY
    linked by target "livox_ros_driver2_node" in directory /home/wy/driver/livox_hap/ws_livox/src/livox_ros_driver2

Is this something wrong？I followed the README of this hub.
Env：Ubuntu 20.04 / ROS Noetic

**Comment by Livox-Infra** [comment]
hi @WangY69 ,
