### ISSUE TITLE
Can't receive any data after "Init lds lidar successfully"

### ISSUE THREAD

**Issue by deeplerming** [Livox-SDK/livox_ros_driver2#121]
![image](https://github.com/Livox-SDK/livox_ros_driver2/assets/127293000/428c40be-55ab-4bc5-b5ba-401db5c7bb1b)
![image](https://github.com/Livox-SDK/livox_ros_driver2/assets/127293000/220f98e4-4c76-4228-9f65-4b5df85f6dab)
"roslaunch livox_ros_driver2 msg_MID360.launch", I can init lidar successfully but can't receiver any data, lidar can be pinged normally ,Any idea what could be wrong?

**Comment by JiaoxianDu** [comment]
Same to me, but it works fine in another ubuntu laptop.

**Comment by JiaoxianDu** [comment]
I got it... I set both lidar ip and network port ip to the same, should not...

**Comment by YnewZ** [comment]
I have the same problem, how do you solve it?

**Comment by deeplerming** [comment]
remember to turn off the firewall first.

**Comment by Divya40404** [comment]
Same issue, did anyone solved the error

**Comment by Kay2333** [comment]
you need change the MID360config.json cmd_data_ip and ip.The ip is 192.168.1.1XX(XX is SN two numbers at last)and change the ip to 192.168.1.5.Last reboot. it will work
