### ISSUE TITLE
How to change Mid-360 lidar staic IP?

### ISSUE THREAD

**Issue by kao-yang** [Livox-SDK/livox_ros_driver2#135]
The MID-360 lidar device static IP is 192.168.1.xx, as xx is last two SN number. Can I change the lidar IP? How to do this?  
For use lidar in multi robots, I want to set all lidar IP to same, for easier set Soft and Hard enviroment.
Thanks for your apply.

**Comment by georgflick** [comment]
You can change it using the Livox Viewer:
https://livox-wiki-en.readthedocs.io/en/latest/data_summary/Livox_data_summary.html#livox-viewer

**Comment by kao-yang** [comment]
Thanks, it works.

**Comment by rss-hiverobots** [comment]
I think I accidentaly changed my Mid-360 IP using Livox Viewer 2. Is there a way to revert it to the original? Or how can i find its new ip?

**Comment by kartikeya13** [comment]
Hi @rss-hiverobots were you able to resolve it? I am facing the same issue?

**Comment by rss-hiverobots** [comment]
Hi @kartikeya13, yes. I used the Livox Live Viewer app to set the original IP back.
