### ISSUE TITLE
MID-360 extrinsic parameter

### ISSUE THREAD

**Issue by kao-yang** [Livox-SDK/livox_ros_driver2#139]
What is the extrinsic parameter of MID-360 between /livox/lidar and /livox/imu ? Where is the center of lidar?

**Comment by TZECHIN6** [comment]
Referring to the manual, the sensor light center is 47mm above the base plate.

For the imu and the sensor light extrinsic parameter, well I do not find it. Might be require them to answer for that.

**Comment by TZECHIN6** [comment]
The position of the IMU chip in the point cloud coordinates is x=11.0 mm, y=23.29 mm, z=-44.12 mm.

according to the manual

**Comment by kao-yang** [comment]
Thanks! Get it!

**Comment by 5uv1n** [comment]
Hello @TZECHIN6 can you link the source you got IMU extrinsic from? I can't seem to find the lidar  to IMU extrinsics.

**Comment by georgflick** [comment]
> Hello [@TZECHIN6](https://github.com/TZECHIN6) can you link the source you got IMU extrinsic from? I can't seem to find the lidar to IMU extrinsics.

@5uvin It's in the manual:
https://terra-1-g.djicdn.com/851d20f7b9f64838a34cd02351370894/Livox/Livox_Mid-360_User_Manual_EN.pdf
Page 15: `The position of the IMU chip in the point cloud coordinates is x=11.0 mm, y=23.29 mm, z=-44.12 mm.`

**Comment by 5uv1n** [comment]
@georgflick Thank you!!

**Comment by 5uv1n** [comment]
Hello guys, Is the orientation of the IMU same as the lidar frame? 
Based on this `The IMU data contains the 3-axis acceleration and 3-axis angular velocity, the directions of which are the same with that of the point cloud coordinates. The position of the IMU chip in the point cloud coordinates is x=11.0 mm, y=23.29 mm, z=-44.12 mm.` If I understand correctly, the orientation between the lidar and IMU frame is identity? Or is there a difference between lidar frame (`livox_frame`) and point cloud coordinates being referred to in the manual?
