### ISSUE TITLE
Where is livox_viewer_2.sh & Livox Viewer 2 for linux? 

### ISSUE THREAD

**Issue by MAVProxyUser** [Livox-SDK/livox_ros_driver2#14]
"livox_viewer_2.sh" can not be found anywhere for MID-360. Please update the documentation with a download link.

![PastedGraphic-1](https://user-images.githubusercontent.com/2904396/214965456-b37db7b0-cc3a-49c7-859a-b3a0ae13cdbe.png)
![PastedGraphic-2](https://user-images.githubusercontent.com/2904396/214965465-48d38073-3d99-4d4d-bb85-0a9782786326.png)

**Comment by qlibp** [comment]
Is livox viewer 2 supports ubuntu16.04? Seems that it's only built for 18.04.

**Comment by FPSychotic** [comment]
it will work in noetic too. @MAVProxyUser they changed the name, remove the dash, there is only a .sh file, is that one, just run that one

**Comment by MAVProxyUser** [comment]
@FPSychotic they only recently in the past month added the proper viewer. 
https://www.livoxtech.com/downloads
![image](https://user-images.githubusercontent.com/2904396/229601717-b5bb6f95-f37e-4712-9be9-cc458133d0ad.png)

Previously this did not exist: https://terra-1-g.djicdn.com/65c028cd298f4669a7f0e40e50ba1131/Mid360/LivoxViewer2%20for%20Ubuntu%20v2.3.0.zip
