### ISSUE TITLE
CPU usage is too high, can it be reduced?

### ISSUE THREAD

**Issue by imoted** [Livox-SDK/livox_ros_driver2#21]
CPU usage is too high, can it be reduced?
Even at i7-1165G7 @ 2.80GHz, it consumes about 200%.

livox ros driver1 was much lower.

OS : Ubuntu 20.04 / 18.04
ROS : ROS1 noetic / melodic
 LiDAR config: 
Same settings as described in the readme, except for IP

**Comment by do335** [comment]
I am facing the same problem.
My nuc11 i7-1165G7 could only reach a frame rate of about 7Hz.
But my i7-10700 runs it at 10Hz.

**Comment by Livox-Infra** [comment]
> CPU usage is too high, can it be reduced? Even at i7-1165G7 @ 2.80GHz, it consumes about 200%.
> 
> livox ros driver1 was much lower.
> 
> OS : Ubuntu 20.04 / 18.04 ROS : ROS1 noetic / melodic LiDAR config: Same settings as described in the readme, except for IP

Some performance optimization has been released in version 1.1.2, please update and try again
