### ISSUE TITLE
livox_ros_driver2/CustomMsg格式的话题发布能被livox_ros_driver/CustomMsg格式的订阅者订阅

### ISSUE THREAD

**Issue by 98huan** [Livox-SDK/livox_ros_driver2#25]
我在测试mid-360的时候发现livox_ros_driver2/CustomMsg格式的话题发布能被livox_ros_driver/CustomMsg格式的订阅者订阅到，这是什么原因？会不会有啥影响？

**Comment by Livox-Infra** [comment]
单纯是因为 topic name 相同所以能够被新旧两个版本的 Driver 订阅到。除了信息冗余以及多占用一点性能之外，没有其它副作用
