### ISSUE TITLE
Is repeating scanning mode supported for mid360?

### ISSUE THREAD

**Issue by leewo0** [Livox-SDK/livox_ros_driver2#36]
The output point cloud makes no difference after changing pattern mode to 1.
Console output filtered by `grep pattern` is listed below.

set scan pattern, handle: 2248255680, scan pattern: 1
successfully set pattern mode, handle: 2248255680, set_bit: 0

**Comment by FPSychotic** [comment]
i dont know if that option is for that, but if you change it in the livox viewer2 will work later in ros, the mode will be active until you change it again. obviously would be better a option as the one you said and it works, but it is a 
workaround

**Comment by leewo0** [comment]
@FPSychotic Thanks for your reply. I checked the lidar settings in the livox viewer2. The `Scan Pattern` had been changed to `Repetitive`(changing the option worked in the ros driver), but the output point cloud is still non repetitive in both livox viewer2 and ros driver. I noticed the firmware version is `13.17.01.11` and the product info is `DevType:Mid-360 FmT` in the setting menu. Is this feature not supported by my mid360?

**Comment by FPSychotic** [comment]
I will check again and check fw version, but quite sure is working

**Comment by FPSychotic** [comment]
Need check but I read about it has one LoL

**Comment by leewo0** [comment]
not supported yet

**Comment by LotfiZ** [comment]
Hi Livox team, 

Are you planning to support Repetitive pattern for the mid 360 ? If yes, can we have a timeline estimation if its possible ? 

Thank you
