### ISSUE TITLE
Is this compatible with ROS1 melodic?

### ISSUE THREAD

**Issue by Tianhao-Liu** [Livox-SDK/livox_ros_driver2#4]
![Screenshot from 2022-10-04 19-34-41](https://user-images.githubusercontent.com/88519622/193773426-abea8d33-b1d2-4bb6-8a06-48c2e3c63983.png)

I got this error but not sure why.

**Comment by OrcunCanDeniz** [comment]
did you manage to solve this?

**Comment by Tianhao-Liu** [comment]
> 

Yep, it turns out to be the wrong IP address in HAP_config.json.
