### ISSUE TITLE
Init lds lidar successfully. but no subsequent data. I need help!

### ISSUE THREAD

**Issue by CQ-Quest** [Livox-SDK/livox_ros_driver2#45]
![image](https://user-images.githubusercontent.com/54696700/236134632-b16c44c1-911a-4aa7-acf1-75c2dfd24539.png)
Init lds lidar successfully. but no subsequent data. I need help!
Ubuntu18.04  melodic
Livox HAP
changed IP and can be pinged normally.
![image](https://user-images.githubusercontent.com/54696700/236135567-55a04154-75df-4bcf-815b-d3cd83811727.png)
use 12V power and no problem with network connection. But no data. 
What should I do?

**Comment by hwan0806** [comment]
Same problem in mid360 case. Did you solved it? I'd appreciate if you can share any solutions!

**Comment by CQ-Quest** [comment]
> 

remain
1.using the 12v dc power
2.check the network interface and sure it working well.
3.trying to remove the crystal head and link it again.check by ping lidar ip itself.(ping 192.168.1.100)

My problem is the step3 and sloved.
