### ISSUE TITLE
1.2 版本 offset_time 有问题 似乎没有很好的同步

### ISSUE THREAD

**Issue by eleboss** [Livox-SDK/livox_ros_driver2#48]
问题是这样，一般来说在msg模式下，offset time最后一个point都会等于 100 MS左右 10HZ，例如1.13版本：
 offset_time: 100152325
    x: -1.30400002003
    y: -6.51300001144
    z: 2.37599992752
    reflectivity: 48
    tag: 0
    line: 3
-
但是在1.2版本下，offset_time 变得非常随机，从0-30秒，一直增加，然后又会reset到0，我觉得这个是一个很严重的bug。反正我现在fast-lio跑不了了。
livox的兄弟们是不是加急看看？

**Comment by Livox-Infra** [comment]
hi @eleboss ，上述问题应该仅出现在 CustomMsg 点云格式下，抱歉。

**Comment by Livox-Infra** [comment]
hot-fix is comming soon...

**Comment by Livox-Infra** [comment]
@eleboss 
[1.2.1](https://github.com/Livox-SDK/livox_ros_driver2/releases/tag/1.2.1) 版本应该修复了上述问题，劳烦试下

**Comment by eleboss** [comment]
1.2.1修复了我提出的问题，感谢。
