### ISSUE TITLE
When Livox Avia support?

### ISSUE THREAD

**Issue by FPSychotic** [Livox-SDK/livox_ros_driver2#8]
When Livox Avia support?

Thanks

**Comment by Livox-Infra** [comment]
hi @FPSychotic , 
Livox ROS Driver2 is not available for Livox Avia now and future...

[Livox ROS Driver](https://github.com/Livox-SDK/livox_ros_driver) fits for it, or is there any problem when using Livox ROS Driver?

**Comment by FPSychotic** [comment]
Basically I want use the repetitive mode of my Livox Avia From 6 months ago with ROS, and I would like use it with ROS2 too. Does allow the ROS1 driver both things?
I asked before a few times but no answer.

**Comment by Livox-Infra** [comment]
hi @FPSychotic , you can try [livox viewer 0.11.0](https://terra-1-g.djicdn.com/65c028cd298f4669a7f0e40e50ba1131/Download/update/Livox%20Viewer%200.11.0.zip) to setup repetitive mode, then use [livox ros2 driver](https://github.com/Livox-SDK/livox_ros2_driver) with ROS2.

**Comment by FPSychotic** [comment]
Ohh, thanks , I didn't know that could be done. I will report back if it works ,maybe helps others
